{% set name = "types-singledispatch" %}
{% set version = "4.1.0.20260408" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f77f487a6e137e986916ca37b36abd8b441561b11088e3cb7b42336fa5a9a47f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  commands:
    - test -f $SP_DIR/singledispatch-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for singledispatch
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
