{% set name = "types-singledispatch" %}
{% set version = "3.7.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-singledispatch-{{ version }}.tar.gz
  sha256: 0780f92954758e663b257a9cfb59cd48cc949175ffa85d2ad8882f4352ef4b56

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/singledispatch-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for singledispatch
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
